[package]
name = "mp1"
version = "0.1.0"
edition = "2021"

[dependencies]
bon = "2.3.0"
tokio = { version = "1.40.0", features = ["full"] }
clap = { version = "4", features = ["derive"] }
futures = "0.3.30"

[profile.release]
opt-level = 3
